# Generated by Django 3.0.7 on 2020-08-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_interface', '0016_auto_20190814_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='req_list_data',
            name='url_address',
            field=models.SlugField(default='/', max_length=255),
            preserve_default=False,
        ),
    ]
