# Generated by Django 3.0.7 on 2020-08-16 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0034_task_project_name_agreement'),
        ('auto_interface', '0017_req_list_data_url_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req_list_data',
            name='data_list_name',
        ),
        migrations.RemoveField(
            model_name='req_list_data',
            name='of_big_model',
        ),
        migrations.RemoveField(
            model_name='req_list_data',
            name='of_big_model_id',
        ),
        migrations.RemoveField(
            model_name='req_list_data',
            name='of_big_on_small_model',
        ),
        migrations.RemoveField(
            model_name='req_list_data',
            name='of_big_on_small_model_id',
        ),
        migrations.AddField(
            model_name='req_list_data',
            name='data_list_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='desk_center.task_project_name'),
            preserve_default=False,
        ),
    ]
