# Generated by Django 3.0.7 on 2020-11-13 00:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0039_auto_20200924_2259'),
        ('auto_interface', '0018_auto_20200816_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_case_listname',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('add_test_name', models.CharField(max_length=255)),
                ('add_test_text', models.TextField()),
                ('create_name', models.CharField(max_length=255)),
                ('create_name_id', models.CharField(max_length=255)),
                ('update_name', models.CharField(max_length=255)),
                ('update_name_id', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('project_name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk_center.task_projects')),
            ],
        ),
    ]
