# Generated by Django 3.0.7 on 2020-06-22 00:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0025_work_historys_task_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='grouping_name_projects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gro_name', models.CharField(max_length=255)),
                ('gro_text', models.TextField(null=True)),
                ('power', models.TextField(null=True)),
                ('create_name', models.CharField(max_length=255)),
                ('update_name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='task_projects',
            name='grouping_name_projects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='desk_center.grouping_name_projects'),
            preserve_default=False,
        ),
    ]
