# Generated by Django 3.0.7 on 2020-06-22 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0029_task_projects_grouping_name_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_projects',
            name='grouping_name_projects',
        ),
    ]
