# Generated by Django 3.0.7 on 2020-07-19 23:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0031_task_projects_grouping_name_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='grouping_name_staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=255)),
                ('smail', models.CharField(max_length=255)),
                ('create_name', models.CharField(max_length=255)),
                ('update_name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk_center.grouping_name_projects')),
            ],
        ),
    ]
