# Generated by Django 3.0.7 on 2020-08-05 00:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0032_grouping_name_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_project_name',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('create_name', models.CharField(max_length=255)),
                ('update_name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='desk_center.task_project_model')),
            ],
        ),
    ]
