# Generated by Django 3.0.7 on 2020-08-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0033_task_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_project_name',
            name='agreement',
            field=models.CharField(default='http', max_length=200),
            preserve_default=False,
        ),
    ]
