# Generated by Django 3.0.7 on 2020-09-23 21:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auto_interface', '0018_auto_20200816_2357'),
        ('desk_center', '0034_task_project_name_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_run_request_historys',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('req_name', models.TextField(null=True)),
                ('req_url', models.TextField(null=True)),
                ('req_param', models.TextField(null=True)),
                ('req_body', models.TextField(null=True)),
                ('req_headers', models.TextField(null=True)),
                ('req_assert', models.TextField(null=True)),
                ('req_html', models.TextField(null=True)),
                ('req_assert_to', models.TextField(null=True)),
                ('execute_sign', models.CharField(max_length=200, null=True)),
                ('run_work_name', models.CharField(max_length=20)),
                ('run_work_fullname', models.CharField(max_length=20)),
                ('task_state', models.CharField(max_length=200, null=True)),
                ('states', models.CharField(max_length=200)),
                ('task_module', models.CharField(max_length=200, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('req_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto_interface.Req_list_data')),
            ],
        ),
    ]
