# Generated by Django 3.0.7 on 2020-09-23 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_interface', '0018_auto_20200816_2357'),
        ('desk_center', '0036_auto_20200923_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_run_request_historys',
            name='req_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auto_interface.Req_list_data'),
            preserve_default=False,
        ),
    ]
