# Generated by Django 3.0.7 on 2020-09-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_center', '0038_auto_20200923_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_run_request_history',
            name='task_module_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work_run_request_history',
            name='task_sort',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='work_run_request_history',
            name='task_sort_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
